### ISSUE TITLE
GNames are invalid

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#11]
Im using the GName found from the tool, to make a SDK, but it says "Gname is invalid"

![image](https://user-images.githubusercontent.com/16446639/58839924-0a598000-8664-11e9-820f-169b25273892.png)

![image](https://user-images.githubusercontent.com/16446639/58839902-f4e45600-8663-11e9-924d-dbf03f5579bb.png)

**Comment by corrm** [comment]
yeah it's will be invalid, check How to use video.
https://github.com/CorrM/Unreal-Finder-Tool#how-to-use

Also check every Question mark that found next to any input

**Comment by ghost** [comment]
@CorrM i followed the Youtube video, is just not valid...
Can you try it yourself?

**Comment by corrm** [comment]
#12
