### ISSUE TITLE
following Gnames are invalid

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#12]
#11 
well, i followed the video, i still get one gobject and one gname, and the gname is still invalid

**Comment by corrm** [comment]
![img](https://6.top4top.net/p_1249yxg9s1.png)
i know the address u get from my tool always will be invalid.
just do as i did in the video. the address tool gives u to help you to get the valid address not more than that.

**Comment by ghost** [comment]
> ![img](https://camo.githubusercontent.com/782bae4cceaaf52f8c0ec6e2cf2111c05f0ea074/68747470733a2f2f362e746f7034746f702e6e65742f705f313234397978673973312e706e67)
> i know the address u get from my tool always will be invalid.
> just do as i did in the video. the address tool gives u to help you to get the valid address not more than that.

i followed everything in the video! still invalid...

**Comment by corrm** [comment]
you get gnames chunk array .?
it's that's right give me a screenshot of memory dump for

**Comment by ghost** [comment]
> you get gnames chunk array .?
> it's that's right give me a screenshot of memory dump for

I figured it out, you need to make the tutorial more clear.
Please do or implement a GName Finder xD
