### ISSUE TITLE
How i can use the generated SDK?

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#15]
i generated the SDK, both internal and external, but how i can build a trainer that adds fullbright, unlimited power (on all levels with Torch/Battery power (rechargeable or not?), (and a god mode to avoid jumpscares) and how i can load that mod/function?

**Comment by corrm** [comment]
pls don't ask this type of questions here.
open an issue if u have a problem with the tool. or feature request.
