### ISSUE TITLE
KurtzPel crashing the program

### ISSUE THREAD

**Issue by RekzaiSharp** [CorrM/Unreal-Finder-Tool#26]
Since the latest release the game "KurzPel" crashes the program, once it is running I can't run the tool anymore, once it is closed everything works again. Here is a dump: https://i.lolisare.life/l6H93.mdmp

**Comment by CppBunny** [comment]
Same issue with Friday the 13th. Tool starts without the game running but crashes as soon as the game starts. Tool also won't open when the game is already running.

`The thread tried to read from or write to a virtual address for which it does not have the appropriate access.`

Previous versions worked perfectly.

**Comment by corrm** [comment]
@RekzaiSharp then the problem when start SDK Gen, then Finder works .?

**Comment by corrm** [comment]
@nnvt can u send dump.

**Comment by CppBunny** [comment]
> @nnvt can u send dump.

Here you go.

[20190609-203859-9000-6180.mdmp.zip](https://github.com/CorrM/Unreal-Finder-Tool/files/3270072/20190609-203859-9000-6180.mdmp.zip)

**Comment by corrm** [comment]
@nnvt for u it's Anti-Cheat problem.

Edit:
try the hot-fix blow it will solve the bug that's case a startup crash.

**Comment by corrm** [comment]
Hot-Fix here [3.0.1](https://github.com/CorrM/Unreal-Finder-Tool/releases/tag/3.0.1).
As i tested by my self on game `KurtzPel` i will close this issue.
