### ISSUE TITLE
Some wrong stuff

### ISSUE THREAD

**Issue by johmarjac** [CorrM/Unreal-Finder-Tool#31]
Okay, so at first I wanna say, AWESOME tool!!!

However some bugs I found. The generated SDK classes all include SDK.h but the SDK.hpp file is generated so it throws thousands of errors. Have to rename SDK.hpp to SDK.h then it works.

Also when a SDK is generated the package counter is increased. But when without closing tool generating another sdk it doesnt reset counter. just a small thing nothing bad

**Comment by corrm** [comment]
thanks for this information that's will help me.
```
However some bugs I found. The generated SDK classes all include SDK.h but the SDK.hpp file is 
generated so it throws thousands of errors. Have to rename SDK.hpp to SDK.h then it works.
```
i already fixed this issues in the other branch `improve-generated-sdk`, and there is more fixes and improves, using sdk will be easy after submit.

```
Also when a SDK is generated the package counter is increased. But when without closing tool 
generating another sdk it doesnt reset counter. just a small thing nothing bad
```
i will fix that.
