### ISSUE TITLE
GNames finder crashes instantly

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#33]
Hello, I want to get back to Fortnite cheating and the SDK generators I find are outdated.
But this one came out very recently and I see you are very active.

![image](https://user-images.githubusercontent.com/51835605/59567992-8c717d80-9042-11e9-9cc0-c2394d2bee8d.png)

https://anonfile.com/1eVf52van4/20190616-142409-7232-9100_mdmp ( Memory dump )

Finding GNames crashes the finder instantly. Is there anything I am doing wrong, or Fortnite is not supported?

**Comment by CorrM** [comment]
it's Anti-Cheat Problem.

**Comment by corrm** [comment]
i,m waiting for release the next version after that u will give it another test. if the same i will see what i can do.

**Comment by corrm** [comment]
can u try this version and send the dump if that same problem
https://github.com/CorrM/Unreal-Finder-Tool/releases/tag/3.0.9

**Comment by corrm** [comment]
Since Games like Fortinte, PUBG using string encryption that's will case a problems with the tool.
