### ISSUE TITLE
ProcessEvent got a exception

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#40]
![image](https://user-images.githubusercontent.com/16446639/60224952-0d234b80-9885-11e9-8b05-1aff90e5bbf7.png)
I dont know what's wrong with the SDK now.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16446639/60267253-1a265600-98ea-11e9-9e2d-4b626e8f94c2.png)
Apparently is related .

**Comment by corrm** [comment]
I changed the `PorcessEvent` pattern

**Comment by ghost** [comment]
Tested

It changed to 51 , annd it caused this:

> ---------------------------
Serialization Error : Action Needed
---------------------------
Corrupt data found, please verify your installation.
---------------------------
OK
---------------------------

**Comment by corrm** [comment]
i will try to get a new pattern or even find another way to get it.
