### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by LeagueRaINi** [CorrM/Unreal-Finder-Tool#43]
game: dauntless
ue version: 4.20
issue: ur tool works completely fine in debug mode but fucks up and crashes 24/7 in release mode

**Comment by corrm** [comment]
be sure u using the last version.
be sure u use the GObjects chunks for this game.

**Comment by LeagueRaINi** [comment]
i'm compiling directly from ur github and like i said when running debug it works completely fine and dumps without errors
also ur pre'compiled release throws dozens of errors every time i minimize & un'minimize it

//edit
```
UEObject* ObjectsStore::GetByAddress(const uintptr_t objAddress)
{
	return GObjObjects.Find(objAddress)->get();
}
```

throws a nullptr in release mode

**Comment by corrm** [comment]
that's mean the game use GObjects chunk and u pick the Wrong address.
i know this game and i already dump sdk for it. just select right gobject address.

**Comment by LeagueRaINi** [comment]
huh ur right i only checked one addy and it looked correct so i didnt bother checking the rest problem is fixed now
the random gui errors still remain in ur pre'compiled release, self compiled is fine

**Comment by corrm** [comment]
random gui errors like .?

**Comment by LeagueRaINi** [comment]
no idea it only makes a minidump and i dont get them when compiling it myself so i cant debug it
