### ISSUE TITLE
Crash on finding GNames

### ISSUE THREAD

**Issue by nReCon** [CorrM/Unreal-Finder-Tool#45]
Game: Monster Energy Supercross The Game 2
Engine Version: 4.20.2.0

The program crashes shortly after I click the "Find" button for GNames.

![unrealfindertool_crash1](https://user-images.githubusercontent.com/3115886/60753148-fdf77880-9fbd-11e9-9f70-cbe9ed3d5b41.png)

Dump:  https://www.dropbox.com/s/3byqdi2hii6yuxh/20190706-091303-31292-6504.mdmp?dl=1

**Comment by corrm** [comment]
#33 it's Duplicate

**Comment by nReCon** [comment]
> 
> 
> #33 it's Duplicate

Did you check the dump ? I did and it's not the same error/exception as the dump from #33, I wouldn't have posted it otherwise.

**Comment by corrm** [comment]
i love to see what about your game.
add me on discord `CorrM#0664`

EDIT:
i reopened the issue until see what's going on.

**Comment by nReCon** [comment]
> 
> 
> i love to see what about your game.
> add me on discord `CorrM#0664`
> 
> EDIT:
> i reopened the issue until see what's going on.

Thanks for re-opening. I've added you.

**Comment by corrm** [comment]
Fixed, thanks for reporting.

c9842672bd15fd61e0abcd14f62cf2acfdb93c97
