### ISSUE TITLE
"Not Valid Process ID. !!"

### ISSUE THREAD

**Issue by ghost** [CorrM/Unreal-Finder-Tool#52]
I'm attempting to dump PUBG, but whenever i press the Find button i get a error saying Not Valid Process Id (I tried multiple different versions, i must just be missing something obvious). 

[video](https://i.gyazo.com/a59aedfb1fbaba21fcb86f31d3839f9e.mp4)

What could be the reason for this? BeDaisy & Battleye services are not running.

**Comment by corrm** [comment]
pubg protected, anyway that's mean UFT can't make a process handle.
