### ISSUE TITLE
A lot UnknownData

### ISSUE THREAD

**Issue by pentium1131** [CorrM/Unreal-Finder-Tool#53]
I use this tool dump the game "Remnant" with config
{
      "name": "UStruct",
      "super": "UField",
      "vars": [
        { "pad_1": "16" },
        { "SuperField": "UStruct*" },
        { "Children": "UField*" },
        { "PropertySize": "int" },
        { "MinAlignment": "int" },
        { "pad_2": "48" }
      ],
      "note": ""
    }
no crash but a lot UnknownData
What should I do?

**Comment by corrm** [comment]
wrong JsonEngine structs
