### ISSUE TITLE
Miss Names

### ISSUE THREAD

**Issue by pentium1131** [CorrM/Unreal-Finder-Tool#54]
Remnant have more than 250k names,but only dump to index 245759

**Comment by songce74** [comment]
@pentium1131 How do you successfully generate Remnant's SDK files. When I do it, the programe crashes every time and throw the same error as https://github.com/CorrM/Unreal-Finder-Tool/issues/44.

**Comment by corrm** [comment]
thanks for @lovellll for his commit https://github.com/CorrM/Unreal-Finder-Tool/pull/56/commits/13115f5f3016dde95c035a94d489232391581ae4
