### ISSUE TITLE
NameDump is incomplete in some games.

### ISSUE THREAD

**Issue by songce74** [CorrM/Unreal-Finder-Tool#55]
I found that in some games NameDump was incomplete(i.e. lost some names). This could be because that in NamesStore.cpp:30 `for (int i = 0; i < 15; ++i)`. The limit for chunks is too small for some games, changing it to 30 or so may fix this problem.
Cheers

**Comment by corrm** [comment]
https://github.com/CorrM/Unreal-Finder-Tool/commit/13115f5f3016dde95c035a94d489232391581ae4
