### ISSUE TITLE
Failed with gen sdk for Deadbydaylight

### ISSUE THREAD

**Issue by MuQoe** [CorrM/Unreal-Finder-Tool#59]

**Comment by MuQoe** [comment]
change every thing 
also the tool cant find the correct GName address as well correct addr base+0x5283794
it just crash when start dump coreobject

**Comment by MuQoe** [comment]
solved 
still GName address is wrong  @CorrM
current json file need to add

	{
      "name": "UStruct",
      "super": "UField",
      "vars": [
		{ "pad_01": "*" },
		{ "pad_02": "*" },
        { "SuperField": "UStruct*" },
        { "Children": "UField*" },
        { "PropertySize": "int" },
        { "MinAlignment": "int" },
        { "pad_1": "64" }
      ],
      "note": ""
    }

**Comment by corrm** [comment]
sorry, i don't have any time, so if u can debug the src and check why that's happen will be good.

**Comment by MuQoe** [comment]
already solved bro  just add the thing to that file

**Comment by MuQoe** [comment]
they change the structure
