### ISSUE TITLE
Wrong GNames address

### ISSUE THREAD

**Issue by Symbai** [CorrM/Unreal-Finder-Tool#60]
Tried this tool on multiple unreal engine games. On ARK it never finds GObject addresses. On Borderlands 2 it crashes and on Moons of Madness it finds everything but says wrong GNames address (there is only one).

I've tried following the video tutorial. Game is paused while scanning. What am I doing wrong?

![image](https://user-images.githubusercontent.com/14368203/69229937-4f279380-0b7e-11ea-91d6-4e0e68c1c1a5.png)
![image](https://user-images.githubusercontent.com/14368203/69229960-5babec00-0b7e-11ea-97aa-49e6fecb0593.png)

**Comment by corrm** [comment]
you use the BaseGnamesAddress so the right address as i think is [07E000**0**].

**Comment by Symbai** [comment]
I clicked on "Find" and this on the screenshot is what your tool provided to me. If it should be a zero at the end instead of an eight, then there is a bug in your tool

**Comment by corrm** [comment]
you can look for **FName** struct in Any **EngineConfig** File, To know data size of each item in GNames
