### ISSUE TITLE
Find Class & Generate Sdk Crash

### ISSUE THREAD

**Issue by RussellJerome** [CorrM/Unreal-Finder-Tool#62]
Whenever I try to generate an SDK or find a Class on Fallen Order, the program crashes. (Engine Version 4.21) I did go into the engine base and switch it to that engine version, along with trying other jsons.
Screenshot error: https://imgur.com/3WwXTsX
Screenshot error: https://imgur.com/BqHKVML
Thanks :P

**Comment by zorftw** [comment]
Same issue here.

![image](https://user-images.githubusercontent.com/19976600/71641591-d2202b80-2c9e-11ea-8adc-c5cf1fd72ec2.png)

Edit: Did some debugging issue is right here
![image](https://user-images.githubusercontent.com/19976600/71641724-bddd2e00-2ca0-11ea-8fc7-5b50b999ecd2.png)

issue at UField

![image](https://user-images.githubusercontent.com/19976600/71641734-d4838500-2ca0-11ea-807a-d6fabb0f1dea.png)
Guess I'll have to change the config, give me a second.

Edit: Config resolved the issue. User please check your config.
OOF
![image](https://user-images.githubusercontent.com/19976600/71642100-a6a13f00-2ca6-11ea-944b-3fac70788e5a.png)

**Comment by corrm** [comment]
It's Game Config Problem.
