### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by DemonRem** [CorrM/Unreal-Finder-Tool#64]
I have an error on startup "Program encountered an issue and was termindated. dump information is located in dumps folder in program directory
[Dumps.zip](https://github.com/CorrM/Unreal-Finder-Tool/files/4236828/Dumps.zip)

**Comment by corrm** [comment]
i need more information, what u did to fire this problem

**Comment by DemonRem** [comment]
solved after recompile the tool

**Comment by Squidbillies** [comment]
I'm receiving the errors on startup.  I'm using the compiled v3.1.0.  How can I get rid of the errors on startup?
